--- #YAML:1.0
name:                D-oh-Year
version:             0.05
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    fields:                        0
    overload:                      0
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
